### ISSUE TITLE
Could you also provide the data files as reaction SMILES?

### ISSUE THREAD

**Issue by UnixJunkie** [Laboratoire-de-Chemoinformatique/Reaction_Data_Cleaning#1]
Hello,

In the data directory, .rsmi (reaction SMILES) format would be highly appreciated.
I think this is the initial format in which D. Lowe released the USPTO.

Best regards,
Francois.

**Comment by ArkadiyLin** [comment]
Good morning.

Reaction smiles is not the best format for that. RDF is a more appropriate
choice to store reactions. Nevertheless, you can always read RDFs with
CGRTools and transform it into reaction smiles within 4 lines of code:

from CGRtools import RDFRead

with RDFRead('myfile.rdf') as ifile:
    data = ifile.read()
    reaction_smiles = [str(r) for r in data]

Pay attention that this may take much RAM. If you have not so much of it,
try to iterate the ifile source. Also, pay attention that you may lose the
data tags like ID, patent number, etc. An additional code is required to
transfer them properly. Also, some preprocessing might be discarded during
formats converging.

пт, 6 авг. 2021 г., 05:34 Francois Berenger ***@***.***>:

**Comment by UnixJunkie** [comment]
Thanks a lot, I will try what you recommend.

**Comment by UnixJunkie** [comment]
It worked:
```python
#!/usr/bin/env python3

import sys
import CGRtools
from CGRtools import RDFRead

input_fn = sys.argv[1]

with RDFRead(input_fn) as input:
    data = input.read()
    for r in data:
        print("%s" % str(r))
```

**Comment by UnixJunkie** [comment]
Is there a way to preserve the atom-atom mapping from the RDF file?

**Comment by UnixJunkie** [comment]
Currently, the produced rsmi file has all mapping deleted.

**Comment by UnixJunkie** [comment]
chemaxon's mview can read the .rdf and store it as .smiles with the mapping info preserved
