### ISSUE TITLE
Imbalanced reactions in the "golden" dataset

### ISSUE THREAD

**Issue by UnixJunkie** [Laboratoire-de-Chemoinformatique/Reaction_Data_Cleaning#2]
Hello,

If I am not mistaken, there are 836 imbalanced reactions in the "golden" dataset.
I am surprised.

Regards,
F.

**Comment by ArkadiyLin** [comment]
Sure, why there shouldn't be any? This is a real data case. It is very rare when a reaction is balanced.

**Comment by UnixJunkie** [comment]
Balanced reactions seem more "golden" to me...
If you are aware of this, not so big deal then.

**Comment by ArkadiyLin** [comment]
"Golden" here means that the established Atom-to-Atom mapping is correct and it was checked manually by human experts, and the reactions themselves are chemically meaningful. A reaction can be unbalanced and it is still considered "Golden" if it is chemically correct in sense of given molecules (reactants and products) as well as given AAM labels. I understand that it might be challenging for DeepLearning to handle such reactions, but this is the real case, not the ideal one.

**Comment by UnixJunkie** [comment]
Ok, thanks for the precision.
